Zap update

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -210,16 +210,16 @@ jobs:
           echo "$TARGET_URL" > scanners/target-url
 
           # Set ZAP options (JSON + HTML report + config file)
-          echo "-J /zap/wrk/zap-report.json -r /zap/wrk/zap-report.html --active-scan true" > scanners/zap-options
+          #echo "-J /zap/wrk/zap-report.json -r /zap/wrk/zap-report.html --active-scan true" > scanners/zap-options
 
           kubectl delete job zap-scan -n app-test --ignore-not-found=true
           kubectl apply -f scanners/zap-job.yaml
 
-          kubectl wait --for=condition=complete job/zap-scan -n app-test --timeout=1800s || {
-            echo "ZAP scan failed or timed out"
-            kubectl describe job zap-scan -n app-test
-            kubectl logs -n app-test -l job-name=zap-scan --tail=100
-          }
+          #kubectl wait --for=condition=complete job/zap-scan -n app-test --timeout=1800s || {
+          #  echo "ZAP scan failed or timed out"
+          #  kubectl describe job zap-scan -n app-test
+          #  kubectl logs -n app-test -l job-name=zap-scan --tail=100
+          #}
 
 
           POD_NAME=$(kubectl get pod -n app-test -l job-name=zap-scan -o jsonpath="{.items[0].metadata.name}")
